apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workspace-k8s.fullname" . }}
  labels:
    {{- include "workspace-k8s.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workspace-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workspace-k8s.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "workspace-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        - name: workspace-login-app
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: registry.digitalocean.com/workspace-login-app/web-app:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: workspace-db-mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workspace-db-mysql
                  key: mysql-root-password
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: workspace-login-api-token
                  key: api-token
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
