{{- if .Values.ingress.enabled -}}
{{- $fullName := include "workspace-k8s.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "workspace-k8s.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - workspace-login.riesenlabs.com
      secretName: workspace-tls
  rules:
    - host: workspace-login.riesenlabs.com 
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
{{- end }}
