"""
NIACC Innovation Workspace Login V2
This file defines the 'Project' class and the associated 'Project_Type' enum.
This class differs from the straight database in that it also contains a list of materials used
Author: Anthony Riesen
"""
from enum import Enum
from typing import List

class ProjectType(Enum):
    """
    Enum that defines the possible project types.
    """
    Personal = 1
    Class = 2
    Entrepreneurial = 3
    Business = 4
    Community = 5
    WorkStudy = 6


class Project:
    """
    Class that defines the data structure of the 'Project' object
    """
    def __init__(
            self, 
            project_id: int, 
            project_name: str, 
            project_description: str, 
            project_type: ProjectType
    ):
        """
        Constructor for 'Project' class

        :param project_id: Unique identifier for each user, generated by the database.
        :param project_name: Unique name for projects @Todo - Perhaps remove unique qualifier
        :param project_description: Description of the project that includes additional details that help distinguish
        this particular project from any other
        :param project_type: Enum value that defines this project's type out of the available options
        """
        self.project_id = project_id
        self.project_name = project_name
        self.project_description = project_description
        self.project_type = project_type

    def __str__(self):
        return f"Project: projectID: {self.project_id}, Name: {self.project_name}," \
               f"Project Description: {self.project_description}, Project Type: {self.project_type}"


class ProjectSummary:
    """ Sub set of the attributes specified on the Project class
    """
    def __init__(self, id: int, name: str):
        self.id=id
        self.name=name

