"""
NIACC Innovation Workspace Login V2
This file defines the 'Visit' class
Author: Anthony Riesen
"""
import datetime as dt

from ws_login_domain import User

from typing import Optional, List
from dataclasses import dataclass

@dataclass
class Visit:
    """
    Class that defines the data structure of the visit object

    Constructor for the 'visit' object
    @Todo Determine if visit_category is needed, if it is a string, or if it is a enum
    :param visit_id: Unique identifier for each visit, generated by the database
    :param user_id: Foreign Key that connects the visit to the user who is visiting
    :param start_time: Timestamp for the login time of the visit
    :param end_time: Timestamp for the logout time of the visit
    """
    visit_id: int
    user_id: int
    start_time: dt.datetime
    end_time: Optional[dt.datetime]

    def is_ended(self) -> bool:
        return self.end_time is not None

